/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-10-31 07:47:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/css/style.css\"/>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/plugins/bootstrap.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"topPanel\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"left-content\"></div>\r\n");
      out.write("\t\t\t<div class=\"right-content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--引入jQuery框架库文件-->\r\n");
      out.write("\t<!-- <script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"http://code.jquery.com/jquery-2.1.3.js\"></script> -->\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/plugins/jquery2.1.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- 引用JQuery分页插件 -->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/plugins/jqPaginator.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar $container;\r\n");
      out.write("\t\tvar $topPanel;\r\n");
      out.write("\t\tvar $leftContent;\r\n");
      out.write("\t\tvar $rightContent;\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$container = $(\"#container\");\r\n");
      out.write("\t\t\t$topPanel=$container.find(\".topPanel\");\r\n");
      out.write("\t\t\t$leftContent = $container.find(\".left-content\");\r\n");
      out.write("\t\t\t$rightContent = $container.find(\".right-content\");\r\n");
      out.write("\t\t\t//加载头部列表\r\n");
      out.write("\t\t\t$topPanel.load(\"common/top.jsp\");\r\n");
      out.write("\t\t\t//加载列表\r\n");
      out.write("\t\t\t$leftContent.load(\"toLeft\", function() {\r\n");
      out.write("\t\t\t\tvar $parent = $(this);\r\n");
      out.write("\t\t\t\t//点击\r\n");
      out.write("\t\t\t\t$parent.find(\".left-item\").on(\"click\", function(e) {\r\n");
      out.write("\t\t\t\t\tvar $this = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//高亮处理\r\n");
      out.write("\t\t\t\t\t$parent.find(\".left-item\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t\t$this.addClass(\"active\");\r\n");
      out.write("\t\t\t\t\t//使用SPA，在一个URL加载两个界面\r\n");
      out.write("\t\t\t\t\t//阻止a标签原有的默认事件\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t//得到a标签href属性的值\r\n");
      out.write("\t\t\t\t\tvar pageRef = $this.find(\"a\").prop(\"href\");\r\n");
      out.write("\t\t\t\t\tvar id= $this.find(\"a\").data(\"id\");\r\n");
      out.write("\t\t\t\t\tconsole.log(\"id:\"+id);\r\n");
      out.write("\t\t\t\t\t//JQuery load页面\r\n");
      out.write("\t\t\t\t\t$rightContent.load(pageRef,{id:id});\r\n");
      out.write("\t\t\t\t}).first().click();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
