/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-11-07 02:50:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>用户管理系统</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#index {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 670px;\r\n");
      out.write("\t/*background-image: url(1.png);*/\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\t/*background-color: rgba(192, 192, 192, 0.8);*/\r\n");
      out.write("\tbackground-color: #ccc;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write(".container .ourname{\r\n");
      out.write("\tflex-basis: 20%;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\t/*background-color: yellow;*/\r\n");
      out.write("\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".container .logo{\r\n");
      out.write("\tflex-basis: 60px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\t/*background-color: red;*/\r\n");
      out.write("\tbackground-image: url(images/logo1.png);\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding-right:60px;\r\n");
      out.write("}\r\n");
      out.write("ul li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t/* font-size: 20px; */\r\n");
      out.write("\tmargin-right:20px;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("}\r\n");
      out.write("ul li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size:16px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write(" ul li:hover, ul li.active\r\n");
      out.write("\t{\r\n");
      out.write("\t/*text-decoration: underline;*/\r\n");
      out.write("}\r\n");
      out.write("a:focus {\r\n");
      out.write("\ttext-decoration: none;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("\t/*text-decoration: underline;*/\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".collapse {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 35%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mission {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 950px;\r\n");
      out.write("\t/*background-image: url(../images/index.jpg);*/\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\t/*overflow-y: scroll;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#index .title-v1, .title-v2 {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 2.4em;\r\n");
      out.write("\tfont-weight:lighter;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 240px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#index .title-v2 button {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.1);\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder:2px solid white;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#index .title-v2 button:hover {\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#index .title-v2 button:active {\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\topacity: 0.5;\r\n");
      out.write("\tborder-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mission {\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("\t/*background-color: #c4f7aa;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brief-introduction {\r\n");
      out.write("\twidth: 88%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liu {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brief-introduction table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brief-introduction tr {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brief-introduction td {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tpadding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".help {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 650px;\r\n");
      out.write("\t/*background-image: url(index1.);*/\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("\tbackground-position: absolute;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\t/*background-color: rgba(30, 30, 30, 0.1);*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 68%;\r\n");
      out.write("\theight: 80%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 120px;\r\n");
      out.write("\t/*background-color: red;*/\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write(".contact .sendtome{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 10%;\r\n");
      out.write("\t/*background-color: red;*/\r\n");
      out.write("\tline-height: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 2.4em;\r\n");
      out.write("\tfont-weight: lighter;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-us {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-us td {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 70px;\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 1.4em;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words input {\r\n");
      out.write("\twidth: 370px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tmargin: 0 0 35px 0;\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.9);\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder-color: rgba(192, 192, 192, 0.2);\r\n");
      out.write("\t/*border: 1px solid rgba(192, 192, 192, 0.2);*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words textarea {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:5px;\r\n");
      out.write("\twidth: 370px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\t/*border-color: rgba(192, 192, 192, 0.8);*/\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.9);\r\n");
      out.write("\tmargin: 0 0 15px 0;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words button {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.2);\r\n");
      out.write("\tborder-color: rgba(192, 192, 192, 0.2);\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tborder-color: rgba(192, 192, 192, 0.2);\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words textarea:hover {\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-words input:hover {\r\n");
      out.write("\tbackground-color: rgba(192, 192, 192, 0.1);\r\n");
      out.write("}\r\n");
      out.write(".nouser{\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #d4e7ba;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".love {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 115px; height: 115px;\r\n");
      out.write("    background: url(images/web_heart_animation.png) 0 0 no-repeat;\r\n");
      out.write("    background-size: 2900%;\r\n");
      out.write("    animation: heart-burst steps(28) 1.2s infinite both;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    left: 360px;\r\n");
      out.write("    bottom: 230px; \r\n");
      out.write("}\r\n");
      out.write("@keyframes heart-burst {\r\n");
      out.write("  0% {\r\n");
      out.write("    background-position: 0%;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    background-position: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top topnav\"\r\n");
      out.write("\t\trole=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t <div class=\"ourname\">\r\n");
      out.write("\t\t\t \t<div class=\"logo\"></div>UMS</div>\r\n");
      out.write("\t\t\t <div class=\"collapse\" id=\"example\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#about\">关于</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#mission\">简介</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#help\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"toLogin\">登录/注册</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<a name=\"about\"></a>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"index\">\r\n");
      out.write("\t\t<div class=\"title-v1\">用 户 管 理 系 统</div>\r\n");
      out.write("\t\t<div class=\"title-v2\">\r\n");
      out.write("\t\t\t<button>Login...</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<iframe frameborder=\"0\" scrolling=\"no\" src=\"index2.html\" width=\"100%\" height=\"500px\"></iframe>\r\n");
      out.write("\t\t\t<div class=\"love\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"mission\" class=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"mission\">\r\n");
      out.write("\t\t\t<div class=\"brief-introduction\">\r\n");
      out.write("\t\t\t\t本用户管理系统是通过用户进行登录管理其他用户的一个系统性系统，登录用户可以有编辑，删除，增加用户等权限，\r\n");
      out.write("\t\t\t\t也可以为用户赋予其他权限，用户操作后将永久从数据库中删除和改动。<br>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"a\"><img src=\"images/login.jpg\" width=\"350px\"><br>登录界面</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"b\"><img src=\"images/register.jpg\" width=\"350px\"><br>注册界面</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"c\"><img src=\"images/index2.jpg\" width=\"350px\"><br>系统首页面</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/operation.jpg\" width=\"350px\"><br>操作界面</td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/append.jpg\" width=\"350px\"><br>添加界面</td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/Headportrait.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"350px\"><br>头像页面</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t本系统由HPE Unversity java2班无敌霸王六枪组合完成<br>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/liu.jpg\" width=\"350px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"230\"><br>无敌霸王六枪</td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/liu1.jpg\" width=\"350px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"230\"><br>双击666</td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/liu2.jpg\" width=\"350px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"230\"><br>认真中...</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"help\" class=\"contacts-section\">\r\n");
      out.write("\t\t<div class=\"help\">\r\n");
      out.write("\t\t\t<div class=\"contact\">\r\n");
      out.write("\t\t\t\t<div class=\"sendtome\">『&nbsp;联系我们&nbsp;』</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact-us\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>地址：遵义市红花岗区重创小镇阿尔泰室</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>电话：+86-8888888888</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>邮件：wbangquan@sina.com</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>集团：无敌霸王枪集团</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact-words\">\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t姓名:<br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t邮件:<br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textareas\">\r\n");
      out.write("\t\t\t\t\t\t\t留言:<br>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"liuyan\" style=\"resize: none; overflow: hidden;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<button>提交</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/plugins/jquery2.1.3.min.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#index\").find(\".title-v2\").find(\"button\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twindow.location.href=\"toLogin\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
